### ISSUE TITLE
Deploy webpage on render

### ISSUE THREAD

**Issue by Hikutaatti** [TVT23SPO-Syksy24-webinaaristit/Movie-React-Website#90]
This requires engine setup, so that we can save our npm files to github beforehand, without render mistaking it to be an "empty project ".

More information on how this can and will be setup is available on discord inside a link in the [#project-setup](https://discordapp.com/channels/1300737703561658428/1309175909860769895) channel

**Comment by ArttuIivari** [comment]
Scrapped due to less importance and time constraints.
